Exercicios Resolvidos Aulas 2 e 3
danielgoncalvesti/progI-2024 pull request #7
Opened 2024-10-06 22:21 UTC by RikelmySander

2024-10-07 13:09 UTC, danielgoncalvesti requested changes
Muito bom para um primeiro pull request.

Revise, por favor, as alterações solicitadas.

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula02/01-estrutura-sequencial/Ex04.py
> +Fahrenheit = float(temperatura * (9/5) + 32)
por convenção, variáveis deve iniciar com letra minúscula.
Fahrenheit -> fahrenheit

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula02/01-estrutura-sequencial/Ex05.py
> +Palavra = input("Digite uma palavra: ")
mesma coisa aqui

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula02/01-estrutura-sequencial/Ex06.py
> +Palavra = input("Digite uma palavra: ")
mesma coisa aqui.

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula02/01-estrutura-sequencial/Ex07.py
> +Frase = input("Digite uma frase: ")
o mesmo aqui

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula02/01-estrutura-sequencial/Ex08.py
> +Num2 = int(input("Digite um número: "))
aqui também

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula02/01-estrutura-sequencial/Ex10.py
> +Num3 = int(input("Digite um numero: "))
letra minúscula

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula03/02-definicao-funcoes/Ex03.py
> +        return "False"
returne True ou False do tipo booleano. Se adicionar aspas, isso vai ser convertido para string. 

Apenas retirar as "" dos dois retornos.

2024-10-07 13:09 UTC, danielgoncalvesti commented on Aula02/01-estrutura-sequencial/Ex11.py
> +Num2 = int(input("Digite um numero: "))
minúscula

2024-10-09 17:34 UTC, RikelmySander reviewed
Esta tudo arrumado agora!

2024-10-09 17:41 UTC, merged